services:
    zerotier:
        image: zerotier/zerotier
        container_name: zerotier-one
        restart: unless-stopped
        devices:
            - /dev/net/tun
        network_mode: host
        volumes:
            - '/var/lib/zerotier-one:/var/lib/zerotier-one'
        cap_add:
            - NET_ADMIN
            - SYS_ADMIN

