services:
  wg-easy:
    environment:
      - WG_HOST=${HOST}
      - PASSWORD_HASH=${PASS}
      - PORT=52000
      - WG_PORT=51000
      - WG_DEFAULT_ADDRESS=10.8.0.x
      - WG_DEFAULT_DNS=192.168.1.202, 1.1.1.1, 8.8.8.8
      # 1400 or we will get SSL errors when trying to connect to our domain
      # https://www.reddit.com/r/WireGuard/comments/g6whsp/ssh_works_but_https_not/
      - WG_MTU=1400
      - WG_DEVICE=ens18
      - WG_ALLOWED_IPS=192.168.10.0/24
      - UI_TRAFFIC_STATS=true
      - UI_CHART_TYPE=1 # (0 Charts disabled, 1 # Line chart, 2 # Area chart, 3 # Bar chart)

    image: ghcr.io/wg-easy/wg-easy
    container_name: wg-easy
    volumes:
      - ./config:/etc/wireguard
    network_mode: host
    ports:
      - "51000:51000/udp"
      - "52000:52000/tcp"
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
      - SYS_MODULE